<a href="https://colab.research.google.com/github/mb8655/Python/blob/main/Google_Maps_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Google Maps API
This a relatively simple API, that does not require any authentication.

The documentation is available at https://developers.google.com/maps/documentation/geocoding/intro

At the simplest version, the endpoint is http://maps.googleapis.com/maps/api/geocode/json and you can put as parameter the "address".

For example, the following call will return the analysis for the address "44 West 4th, Ste 8-84, Manhattan, NY, USA"

In [1]:
import requests
import time

In [2]:
import requests

GOOGLE_MAPS_API_URL = 'https://maps.googleapis.com/maps/api/geocode/json'
params = {
    'address': '4 Johnson Dr',
    'key': 'AIzaSyAwAQwNRabOhjJxgB9zkogV-BKgbAnjxUk'
}

resp = requests.get(GOOGLE_MAPS_API_URL, params = params)
resp.json()

{'results': [{'address_components': [{'long_name': '4',
     'short_name': '4',
     'types': ['street_number']},
    {'long_name': "Johnson's Drive",
     'short_name': "Johnson's Dr",
     'types': ['route']},
    {'long_name': 'Elmstead Market',
     'short_name': 'Elmstead Market',
     'types': ['locality', 'political']},
    {'long_name': 'Colchester',
     'short_name': 'Colchester',
     'types': ['postal_town']},
    {'long_name': 'Essex',
     'short_name': 'Essex',
     'types': ['administrative_area_level_2', 'political']},
    {'long_name': 'England',
     'short_name': 'England',
     'types': ['administrative_area_level_1', 'political']},
    {'long_name': 'United Kingdom',
     'short_name': 'GB',
     'types': ['country', 'political']},
    {'long_name': 'CO7 7AL',
     'short_name': 'CO7 7AL',
     'types': ['postal_code']}],
   'formatted_address': "4 Johnson's Dr, Elmstead Market, Colchester CO7 7AL, UK",
   'geometry': {'location': {'lat': 51.88255299999999, 'lng': 0.997181},
    'location_type': 'ROOFTOP',
    'viewport': {'northeast': {'lat': 51.8839690302915,
      'lng': 0.9985103302915018},
     'southwest': {'lat': 51.8812710697085, 'lng': 0.9958123697084977}}},
   'navigation_points': [{'location': {'latitude': 51.8826251,
      'longitude': 0.9971599}}],
   'place_id': 'ChIJc9I4fK8P2UcRrU-XiikARo0',
   'types': ['premise', 'street_address']}],
 'status': 'OK'}

In [3]:
#other examples

def call_google_api(address):

    GOOGLE_MAPS_API_URL = 'https://maps.googleapis.com/maps/api/geocode/json'
    params = {
        'address': address,
        'region': 'usa',
        'key': 'AIzaSyAwAQwNRabOhjJxgB9zkogV-BKgbAnjxUk'
    }
    req = requests.get(GOOGLE_MAPS_API_URL, params=params)

    results = req.json()

    # Use the first result
    if 'results' in results and len(results['results'])>0:
        result = results['results'][0]
        return result
    else:
        # We got nothing back, let's wait a bit
        time.sleep(2)
        return None

In [4]:
call_google_api("Soho, New York, NY")

{'address_components': [{'long_name': 'SoHo',
   'short_name': 'SoHo',
   'types': ['neighborhood', 'political']},
  {'long_name': 'Manhattan',
   'short_name': 'Manhattan',
   'types': ['political', 'sublocality', 'sublocality_level_1']},
  {'long_name': 'New York',
   'short_name': 'New York',
   'types': ['locality', 'political']},
  {'long_name': 'New York County',
   'short_name': 'New York County',
   'types': ['administrative_area_level_2', 'political']},
  {'long_name': 'New York',
   'short_name': 'NY',
   'types': ['administrative_area_level_1', 'political']},
  {'long_name': 'United States',
   'short_name': 'US',
   'types': ['country', 'political']}],
 'formatted_address': 'SoHo, New York, NY, USA',
 'geometry': {'bounds': {'northeast': {'lat': 40.7283442, 'lng': -73.9958967},
   'southwest': {'lat': 40.7189454, 'lng': -74.0054619}},
  'location': {'lat': 40.7245908, 'lng': -74.00191740000001},
  'location_type': 'APPROXIMATE',
  'viewport': {'northeast': {'lat': 40.7283442, 'lng': -73.9958967},
   'southwest': {'lat': 40.7189454, 'lng': -74.0054619}}},
 'place_id': 'ChIJ8-JRXoxZwokRGPiQ9Ek0L84',
 'types': ['neighborhood', 'political']}

In [5]:
call_google_api("Jupiter, Florida")

{'address_components': [{'long_name': 'Jupiter',
   'short_name': 'Jupiter',
   'types': ['locality', 'political']},
  {'long_name': 'Palm Beach County',
   'short_name': 'Palm Beach County',
   'types': ['administrative_area_level_2', 'political']},
  {'long_name': 'Florida',
   'short_name': 'FL',
   'types': ['administrative_area_level_1', 'political']},
  {'long_name': 'United States',
   'short_name': 'US',
   'types': ['country', 'political']}],
 'formatted_address': 'Jupiter, FL, USA',
 'geometry': {'bounds': {'northeast': {'lat': 26.9708801, 'lng': -80.056935},
   'southwest': {'lat': 26.882486, 'lng': -80.181378}},
  'location': {'lat': 26.9318533, 'lng': -80.1023696},
  'location_type': 'APPROXIMATE',
  'viewport': {'northeast': {'lat': 26.9708801, 'lng': -80.056935},
   'southwest': {'lat': 26.882486, 'lng': -80.181378}}},
 'place_id': 'ChIJfW8aRDUz2YgRIZqJ_29IUdw',
 'types': ['locality', 'political']}

In [6]:
def get_formatted_address(address):
    google_result = call_google_api(address)
    if google_result == None:
        return None
    return google_result['formatted_address']

In [7]:
def get_lon_lat(address):
    google_result = call_google_api(address)
    if google_result == None:
        return None
    return google_result['geometry']['location']

In [8]:
address = "547 Riverside Drive, New York, NY"
get_formatted_address(address)

'547 Riverside Dr, New York, NY 10027, USA'

In [9]:
address2 = '416 philadelphia drive, jupiter florida'
get_formatted_address(address2)

'416 Philadelphia Dr, Jupiter, FL 33458, USA'

In [11]:
get_lon_lat(address2)

{'lat': 26.9393118, 'lng': -80.1041219}

In [10]:
get_lon_lat(address)

{'lat': 40.8151021, 'lng': -73.9609174}

In [12]:
address = "44 W 4th Street, New York"
get_formatted_address(address)

'44 W 4th St, New York, NY 10012, USA'

In [13]:
address = "44 W Fourth Street, New York"
get_formatted_address(address)

'44 W 4th St, New York, NY 10012, USA'

In [14]:
address = "84 Wooster, Ste 703, New York"
get_formatted_address(address)

'84 Wooster St #703, New York, NY 10012, USA'

##Exercise
Below you can find a list of 50 addresses in New York. The addresses do not contain the zip code, and are not well-formatted. Using the Google Maps API, as listed above, generate the well-formatted address for each address. Also generate the long/lat coordinates for the address.

Important: The Google API listed above is not authenticated. To avoid abuse, when it receives large number of requests, it tends to return nothing. You may want to structure your code to check for this behavior, and retry if necessary.

In [15]:
address_list = ['2508A BROADWAY, QUEENS',  '1859 WESTCHESTER AVENUE, BRONX',
                '113 WEST  116 STREET, MANHATTAN',  '157 PROSPECT PARK SOUTH WEST, BROOKLYN',
                '12707 MERRICK BOULEVARD, QUEENS',  '422 EAST   75 STREET, MANHATTAN',
                '253 WEST   42 STREET, MANHATTAN',  '1027 WESTCHESTER AVE, BRONX',
                '811 9 AVENUE, MANHATTAN',  '717 KINGS HIGHWAY, BROOKLYN',
                '13529 40TH RD, QUEENS',  '4417 NEW UTRECHT AVE, BROOKLYN',  '1688 EAST   16 STREET, BROOKLYN',
                '1634 CROSBY AVE, BRONX',  '218 PARKSIDE AVE, BROOKLYN',  '1307 ARTHUR KILL ROAD, STATEN ISLAND',
                '1162 FIRST AVENUE, MANHATTAN',  '5814 ROOSEVELT AVE, QUEENS',  '872 A FLATBUSH AVE, BROOKLYN',
                '631 WILSON AVE, BROOKLYN',  '1093 JACKSON AVENUE, QUEENS',  '465 WEST   51 STREET, MANHATTAN',
                '345 ADAMS ST, BROOKLYN',  '1374 BOSTON ROAD, BRONX',  '71 7 AVENUE SOUTH, MANHATTAN',
                '520 BAY ST, STATEN ISLAND',  '623 GRAND STREET, BROOKLYN',  '11000 ROCKAWAY BOULEVARD, QUEENS',
                '2927 40 ROAD, QUEENS',  '570 8 AVENUE, MANHATTAN',  '4819 VERNON BLVD, QUEENS',
                '1 WORLDS FAIR MARINA, QUEENS',  '2342 ARTHUR AVENUE, BRONX',  '54 PEARL STREET, MANHATTAN',
                '4012 QUEENS BOULEVARD, QUEENS',  '691 TENTH AVE, MANHATTAN',  '226 E 14TH ST, MANHATTAN',
                '3 GREENWICH AVENUE, MANHATTAN',  '2172 86TH ST, BROOKLYN',  '875 10 AVENUE, MANHATTAN',
                'NKA JFK INTERNATIONAL AIRPORT, QUEENS',  '70 SOUTH ST, MANHATTAN',  '3520 FARRINGTON ST, QUEENS',
                '12696 WILLETS POINT BOULEVARD, QUEENS',  '925 ALLERTON AVENUE, BRONX',  '98 3 AVENUE, MANHATTAN',
                '8805 ASTORIA BLVD, QUEENS',  '12 PENN STATION, MANHATTAN',  '138 DIVISION STREET, MANHATTAN',
                '7047 PARSONS BOULEVARD, QUEENS']

In [16]:
# prompt: generate the well-formatted address for each address above. Also generate the long/lat coordinates for the address.

import pandas as pd

formatted_addresses = []
lon_lats = []

for address in address_list:
  formatted_address = get_formatted_address(address)
  lon_lat = get_lon_lat(address)
  formatted_addresses.append(formatted_address)
  lon_lats.append(lon_lat)

df = pd.DataFrame({'Original Address': address_list, 'Formatted Address': formatted_addresses, 'Lon/Lat': lon_lats})
df

,Original Address,Formatted Address,Lon/Lat
0,"2508A BROADWAY, QUEENS","2508A Broadway, Astoria, NY 11106, USA","{'lat': 40.7631113, 'lng': -73.9282437}"
1,"1859 WESTCHESTER AVENUE, BRONX","1859 Westchester Ave, Bronx, NY 10472, USA","{'lat': 40.83280990000001, 'lng': -73.8639364}"
2,"113 WEST 116 STREET, MANHATTAN","113 W 116th St, New York, NY 10026, USA","{'lat': 40.8025601, 'lng': -73.9502641}"
3,"157 PROSPECT PARK SOUTH WEST, BROOKLYN","157 Prospect Park Southwest, Brooklyn, NY 1121...","{'lat': 40.6547785, 'lng': -73.9735675}"
4,"12707 MERRICK BOULEVARD, QUEENS","12707 Merrick Blvd, Jamaica, NY 11434, USA","{'lat': 40.6816968, 'lng': -73.7651812}"
5,"422 EAST 75 STREET, MANHATTAN","422 E 75th St, New York, NY 10021, USA","{'lat': 40.7691615, 'lng': -73.9537079}"
6,"253 WEST 42 STREET, MANHATTAN","253 W 42nd St, New York, NY 10036, USA","{'lat': 40.7572074, 'lng': -73.98914979999999}"
7,"1027 WESTCHESTER AVE, BRONX","1027 Westchester Ave, Bronx, NY 10459, USA","{'lat': 40.8241622, 'lng': -73.8932458}"
8,"811 9 AVENUE, MANHATTAN","811 9th Ave, New York, NY 10019, USA","{'lat': 40.76587550000001, 'lng': -73.98753359..."
9,"717 KINGS HIGHWAY, BROOKLYN","717 Kings Hwy, Brooklyn, NY 11223, USA","{'lat': 40.6065992, 'lng': -73.96504999999999}"
10,"13529 40TH RD, QUEENS","135-29 40th Rd, Flushing, NY 11354, USA","{'lat': 40.7588885, 'lng': -73.8306151}"
11,"4417 NEW UTRECHT AVE, BROOKLYN","4417 New Utrecht Ave, Brooklyn, NY 11219, USA","{'lat': 40.6401676, 'lng': -73.9941059}"
12,"1688 EAST 16 STREET, BROOKLYN","1688 East 16th Street, Brooklyn, NY 11229, USA","{'lat': 40.6084776, 'lng': -73.9575062}"
13,"1634 CROSBY AVE, BRONX","1634 Crosby Ave, Bronx, NY 10461, USA","{'lat': 40.8450565, 'lng': -73.8305802}"
14,"218 PARKSIDE AVE, BROOKLYN","218 Parkside Ave, Brooklyn, NY 11226, USA","{'lat': 40.6552345, 'lng': -73.9605156}"
15,"1307 ARTHUR KILL ROAD, STATEN ISLAND","1307 Arthur Kill Rd, Staten Island, NY 10312, USA","{'lat': 40.5655321, 'lng': -74.1840474}"
16,"1162 FIRST AVENUE, MANHATTAN","1162 1st Ave., New York, NY 10065, USA","{'lat': 40.7624127, 'lng': -73.9596064}"
17,"5814 ROOSEVELT AVE, QUEENS","5814 Roosevelt Ave, Woodside, NY 11377, USA","{'lat': 40.74514, 'lng': -73.9060669}"
18,"872 A FLATBUSH AVE, BROOKLYN","872A Flatbush Ave, Brooklyn, NY 11226, USA","{'lat': 40.6508378, 'lng': -73.9590922}"
19,"631 WILSON AVE, BROOKLYN","631 Wilson Ave, Brooklyn, NY 11207, USA","{'lat': 40.6897595, 'lng': -73.9060594}"
20,"1093 JACKSON AVENUE, QUEENS","1093 Jackson Ave, Long Island City, NY 11101, USA","{'lat': 40.7432644, 'lng': -73.9516319}"
21,"465 WEST 51 STREET, MANHATTAN","465 W 51st St, New York, NY 10019, USA","{'lat': 40.7653447, 'lng': -73.99075069999999}"
22,"345 ADAMS ST, BROOKLYN","345 Adams St, Brooklyn, NY 11201, USA","{'lat': 40.692752, 'lng': -73.9885422}"
23,"1374 BOSTON ROAD, BRONX","1374 Boston Rd, Bronx, NY 10456, USA","{'lat': 40.8323407, 'lng': -73.89811379999999}"
24,"71 7 AVENUE SOUTH, MANHATTAN","71 7th Ave S, New York, NY 10014, USA","{'lat': 40.732236, 'lng': -74.00331299999999}"
25,"520 BAY ST, STATEN ISLAND","520 Bay St, Staten Island, NY 10304, USA","{'lat': 40.6290899, 'lng': -74.0769641}"
26,"623 GRAND STREET, BROOKLYN","623 Grand St, Brooklyn, NY 11211, USA","{'lat': 40.7115484, 'lng': -73.94714619999999}"
27,"11000 ROCKAWAY BOULEVARD, QUEENS","11000 Rockaway Blvd, South Ozone Park, NY 1142...","{'lat': 40.6738714, 'lng': -73.83268509999999}"
28,"2927 40 ROAD, QUEENS","29-27 40th Rd, Long Island City, NY 11101, USA","{'lat': 40.7514151, 'lng': -73.9351158}"
29,"570 8 AVENUE, MANHATTAN","570 8th Ave, New York, NY 10018, USA","{'lat': 40.7547171, 'lng': -73.99133599999999}"
30,"4819 VERNON BLVD, QUEENS","48-19 Vernon Blvd, Long Island City, NY 11101,...","{'lat': 40.7434607, 'lng': -73.95344949999999}"
31,"1 WORLDS FAIR MARINA, QUEENS","1 Marina Rd, Corona, NY 11368, USA","{'lat': 40.761224, 'lng': -73.857806}"
32,"2342 ARTHUR AVENUE, BRONX","2342 Arthur Ave, Bronx, NY 10458, USA","{'lat': 40.8541344, 'lng': -73.8884775}"
33,"54 PEARL STREET, MANHATTAN","54 Pearl St, New York, NY 10004, USA","{'lat': 40.7033808, 'lng': -74.01135219999999}"
34,"4012 QUEENS BOULEVARD, QUEENS","40-12 Queens Blvd, Sunnyside, NY 11104, USA","{'lat': 40.7433503, 'lng': -73.9239126}"
35,"691 TENTH AVE, MANHATTAN","691 10th Ave, New York, NY 10036, USA","{'lat': 40.7630974, 'lng': -73.9933266}"
36,"226 E 14TH ST, MANHATTAN","226 E 14th St, New York, NY 10003, USA","{'lat': 40.7326152, 'lng': -73.98620609999999}"
37,"3 GREENWICH AVENUE, MANHATTAN","3 Greenwich Ave, New York, NY 10014, USA","{'lat': 40.7338471, 'lng': -73.9998667}"
38,"2172 86TH ST, BROOKLYN","2172 86th St, Brooklyn, NY 11214, USA","{'lat': 40.6019756, 'lng': -73.9944656}"
39,"875 10 AVENUE, MANHATTAN","875 10th Ave, New York, NY 10019, USA","{'lat': 40.7693748, 'lng': -73.988709}"
40,"NKA JFK INTERNATIONAL AIRPORT, QUEENS","John F. Kennedy International Airport (JFK), Q...","{'lat': 40.6446124, 'lng': -73.7797278}"
41,"70 SOUTH ST, MANHATTAN","70 South St, New York, NY 10270, USA","{'lat': 40.7051725, 'lng': -74.0053083}"
42,"3520 FARRINGTON ST, QUEENS","35-20 Farrington St, Flushing, NY 11354, USA","{'lat': 40.7637988, 'lng': -73.83181119999999}"
43,"12696 WILLETS POINT BOULEVARD, QUEENS","12696 Willets Point Blvd, Queens, NY 11368, USA","{'lat': 40.7579786, 'lng': -73.8419918}"
44,"925 ALLERTON AVENUE, BRONX","925 Allerton Ave, Bronx, NY 10469, USA","{'lat': 40.8657387, 'lng': -73.8602861}"
45,"98 3 AVENUE, MANHATTAN","98 Third Ave, Bronx, NY 10451, USA","{'lat': 40.8096187, 'lng': -73.92936399999999}"
46,"8805 ASTORIA BLVD, QUEENS","88-05 Astoria Blvd, Flushing, NY 11370, USA","{'lat': 40.7643619, 'lng': -73.880911}"
47,"12 PENN STATION, MANHATTAN","Penn Station, New York, NY 10119, USA","{'lat': 40.750568, 'lng': -73.993519}"
48,"138 DIVISION STREET, MANHATTAN","138 Division St, New York, NY 10002, USA","{'lat': 40.714555, 'lng': -73.9915134}"
49,"7047 PARSONS BOULEVARD, QUEENS","70-47 Parsons Blvd, Fresh Meadows, NY 11365, USA","{'lat': 40.7309922, 'lng': -73.8100284}"